// Regenerates docs/copy.md (German on-screen copy + English translation + timings) from timeline.js.
const fs = require('fs'), path = require('path');
const TL = require('../project/src/data/timeline.js');
const EN = {
  d1: 'Too risky!', d2: 'No idea how it works …', d3: 'Way too much stress', money: 'You need loads of money for that!', d5: "That's something other people do.",
  h1: 'Start your own company?', h2: 'Not me …', c1: 'Sound familiar?',
  s_k: 'NEW STUDY · BERTELSMANN STIFTUNG', s_h1: 'What do', s_h2: '14- to 25-year-olds', s_h3: 'think about starting a business?',
  s_n: '1,763 young people + 1,325 apprentices', s_n2: 'surveyed online · spring 2026', s_stamp: 'REPRESENTATIVE',
  q_h: 'Self-employed by 30?', c2: 'Imagine 100 young people:', q_big: 'NEARLY 4 IN 10', q_sub: 'can imagine starting a business.', c3: "Imagining isn't founding – but it's a start.",
  b_h: 'What holds the others back?', b_base: "Respondents who can't imagine starting a business", b_multi: 'Multiple answers possible',
  b_tw: 'And money? Hardly a problem.', b_stamp: 'UNDER 10 %', c4: 'Not even one in ten mentions start-up capital.',
  g_h: 'The good news:', g_a: 'Knowledge can be learned.', g_a_st: 'SOLVABLE', g_a1: 'Workshops & student companies', g_a2: 'Founder info via social media',
  g_b: 'Stress can be managed.', g_b_st: 'SOLVABLE', g_b1: 'Free counselling, e.g. Federal Employment Agency, youth career services', g_b2: 'Stress-prevention courses & apps from health insurers',
  c5: 'The study recommends: entrepreneurial thinking in every type of school.',
  m_h: 'And young people are getting started:', m_sub: 'Share of 18- to 24-year-olds who are starting or have recently started a business', m_src: 'Source: Global Entrepreneurship Monitor (GEM) 2025/26', c6: 'Nearly doubled – in just one year.',
  e_k: 'Your next step:', e_t: 'Young Founders Network', e_s: 'Community for young founders under 25', e_b: 'supported by gen now · a project of the Bertelsmann Stiftung (logo card)', e_url: 'youngfounders.network', e_hand: 'check it out!',
  e_src: 'Source: Bertelsmann Stiftung (2026), "Gründungsaufbruch der jungen Generation"; GEM 2025',
};
const GROUP_EN = ['firmly intend to', "can imagine it, but not sure yet", 'rather not, but not ruled out', 'not an option', 'have already done it'];
const ROW_EN = ['too insecure – would rather be employed', 'too little knowledge about founding', 'fear of too much stress'];
const TITLES = { hook: 'Hook', study: 'The study', crowd: 'The big number', barriers: 'What holds people back', good: 'The good news', gem: 'Real-world payoff', end: 'Next step' };
const kind = (i) => ({ caption: ' *(caption)*', stamp: ' *(stamp)*', hand: ' *(handwritten)*', credit: ' *(fine print)*' }[i.type] || '');
const one = (s) => s.replace(/\n/g, ' ').replace(/unter- nehmerisches/, 'unternehmerisches');
let md = `# On-screen copy – German original + English translation (gen now version)\n\nGenerated by \`node tools/copy_doc.js\` from \`project/src/data/timeline.js\` (the source of truth; edit text there). Runtime ${TL.duration} s · 1080×1920 · 30 fps. **t** = when the element appears (s). Timings are paced by \`tools/pace.js\`: lines arrive one after another at a spoken rhythm across each slide, and every line stays readable for at least words ÷ 3 + 0.5 s. Figures are documented in \`docs/facts.md\`.\n`;
TL.scenes.forEach((s, si) => {
  md += `\n## ${si + 1} · ${TITLES[s.id]} (${s.start}–${s.end} s) – ${s.bg}\n\n| t | German (on screen) | English |\n|---|---|---|\n`;
  const rows = TL.items.filter((i) => i.scene === s.id).map((i) => [i.in, one(i.text) + kind(i), EN[i.id] || '']);
  if (s.id === 'crowd') TL.crowd.groups.forEach((g, k) => rows.push([TL.crowd.tagsIn[k], `${g.text} – ${g.label}`, `${g.text} – ${GROUP_EN[k]}`]));
  if (s.id === 'barriers') {
    TL.barriers.rows.forEach((r, k) => rows.push([r.in, `${r.text} – ${r.label}`, `${r.text.replace('rund', 'around')} – ${ROW_EN[k]}`]));
    const p = TL.items.find((i) => i.id === 'money').path;
    rows.push([p[p.length - 1].t, '*(the note from the hook returns and is crossed out)* Dafür brauchst du viel Geld!', 'You need loads of money for that!']);
  }
  if (s.id === 'study') rows.push([TL.study.card.in, '*(survey card)* FRAGEBOGEN', 'QUESTIONNAIRE']);
  if (s.id === 'gem') TL.gem.bars.forEach((b) => rows.push([b.in, `${b.year}: ${b.text}`, `${b.year}: ${b.text.replace('knapp', 'just under').replace('über', 'over')}`]));
  rows.sort((a, b) => a[0] - b[0]).forEach(([t, de, en]) => (md += `| ${(+t).toFixed(2)} | ${de} | ${en} |\n`));
});
md += `\n## Notes on wording\n\n- Informal *du* throughout. "Gründer:innen" is used for gender-inclusive wording, and "jede:r Zehnte" in the same style.\n- "Can imagine" (vorstellen) is kept separate from "will found" (gründen): scene 3 says so explicitly.\n- The barrier percentages are multiple-choice answers, so they're never added up, and the screen says „Mehrfachnennungen möglich".\n- The survey figures and the GEM figure are shown as separate facts with separate sources. No causal link is implied.\n- The source credit on the last slide is fine print: it's visible for the whole slide (about 5 s), while the URL is held for at least 3.2 s.\n- The education-gap scene (optional in the brief) was left out because its figures could not be verified (see \`docs/facts.md\`).\n`;
fs.writeFileSync(path.resolve(__dirname, '..', 'docs', 'copy.md'), md);
console.log('wrote docs/copy.md');
